### ISSUE TITLE
Missing Dataset and Code Release Promised by Authors

### ISSUE THREAD

**Issue by LucaLumetti** [huiminxiong/TSegFormer#6]
The authors of the paper referenced in their response available at [this link](https://conferences.miccai.org/2023/papers/678-Paper2739.html) commitment to release a partial version of their dataset as well as the associated code. Specifically, they stated:

> The dataset is not publicly available due to privacy concerns. We will release a partial version of it. Q4: Code A4: We will make the code public.

However, it has been over a year since the paper's acceptance, and neither the dataset nor the code has been made available. This lack of release is hindering further research and reproducibility efforts within the community.

Could you please provide an update on the status of the dataset and code release? Any information on the timeline or potential issues delaying the release would be greatly appreciated.

**Comment by huiminxiong** [comment]
Apologies for the long wait. Due to some previous reasons, we were unable to make it public earlier. Now, we have released the source code. If you find it useful, please consider citing our work.
